### ISSUE TITLE
Document the flags that can be set on the contour binary

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#1003]
**Describe the solution you'd like**
Contour exposes a set of flags that can be used to configure the behavior of the ingress controller. Historically, I have resorted to looking at the source code under `cmd/` to find the flags I need to tweak. 

Ideally, these flags are documented for users that might not understand Go.

**Comment by davecheney** [comment]
I don’t want to duplicate the output of

contour serve —help

It will just get out of date.

**Comment by alexbrand** [comment]
That is an excellent point. Unfortunately, I've seen multiple instances of people asking how to configure Envoy to listen on ports other than 80/443. What do you think about capturing that use case in `docs/deploy-options.md`?

**Comment by stevesloka** [comment]
@alexbrand I think to document why you'd use these different flags and when would be helpful in that deployment section.

**Comment by davecheney** [comment]
How about this as a middle ground, we set each of the flags explicitly to their default values in the deployment examples? 

The bottom line is there is no test for a markdown file or a deployment/ yaml example. I know people have problems finding the right values to set, but we have a long history of bugs caused by these files getting out of date.

**Comment by alexbrand** [comment]
Exposing the flags in the deployment sounds good to me. I don't necessarily think we have to expose all of them. Seems like the most common ask we get is the one around configuring the listening ports, so I think I would start there. I'll open a PR to explicitly set those in the deployment files.
