### ISSUE TITLE
tcp proxy connections need idle timeout setting

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1074]
#1070 set the idle timeout for http connections to 60 seconds. We should do the same for TCP connections. The timeout should probably be longer than 60 seconds as the semantics for tcp connections are different from the keep alive behaviour of an idle http connection.

**Comment by youngnick** [comment]
TCP keepalive is done by the operating system, based on if it's turned on or not on a per-socket level, generally. However, if it is turned on, all the major operating systems (Linux, Windows, MacOS, *BSD) default the keepidle timeout ( the length of time a TCP connection can be idle before keepalives start) at two hours (ie 7200 sec).

Because of this, our idle timeout need to be a bit bigger than the default keepalive timeout, I'm going to put a finger in the air and call it 2.5 hours to start with.

Given that Envoy's default is to disable idle timeouts altogether, this should help with removing some possible connection leaks as listeners rotate.

**Comment by davecheney** [comment]
Make it so, we can adjust the timeout later if/when we get feedback from the field.

**Comment by youngnick** [comment]
Will do.

**Comment by moderation** [comment]
Is there any impact of Envoy introducing a default 60 minutes timeout for TCP @youngnick? https://github.com/envoyproxy/envoy/pull/8705

**Comment by davecheney** [comment]
@moderation tracked as #1907
