### ISSUE TITLE
[spike] Investigate if we can use :* syntax in domain matching

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1125]
One of the oldest issues we have on this project is related to how Envoy handles `Host: ` headers which include a `:port` suffix. #210, #398, #353 and many more.

[A recent comment](https://github.com/envoyproxy/envoy/issues/886#issuecomment-492824085) suggests that we may be able to specify
```
domains: []string{"host", "host:*"}
```
instead of tracking and hard coding the port the listener connected to this routing is using, can we use the `:*` syntax instead?

This is a spike to see if this is possible, if it will work for both HTTP and HTTPS, and if so scope the work to remove completely or partially the mechanisms for configuring and tracking the listening port's number throughout Contour.

_nb_: The resolution of this ticket is either closing this issue with a comment if it is not possible to use this syntax. Bonus points for replying to the original commenter. If this is something we can use, please scope the work necessary in one or more new issues -- we may choose to do it over several releases, especially if deprecating flags are involved.

**Comment by youngnick** [comment]
Okay, I have a branch that will change the VirtualHost generation so that it will always add the `hostname` and `hostname:*` to the `domains` part of the config, instead of using the given port.

Things I've been able to confirm:
- Envoy accepts the config
- Traffic routes correctly to bare hostname requests (ie Host header is `example.com`)
- Traffic routes correctly to hostnames with ports (ie Host header is `example.com:80` or `example.com:443`, or even `example.com:31273`)
- Kubernetes Services that are not available on whatever the value of `--envoy-service-http-port` or `--envoy-service-https-port` still work.

Changes that we'll need to make to actually make this a thing:
- Fix all the tests to expect `example.com:*` instead of `example.com:<port>`
- Remove the wiring that brings the ports down to the VIrtualHost. This will include deprecating some command line flags, like `--envoy-service-http-port` and `--envoy-service-https-port`, at least.
- remove `minikube.md` and update documentation with minikube and kind examples.
- Other stuff I don't know about.

**Comment by davecheney** [comment]
Nice result. Make it so.
