### ISSUE TITLE
Contour serve command outputs debug logs by default, which can be unnecessary noisy in large scale setups

### ISSUE THREAD

**Issue by rochacon** [heptio/contour#1134]
**Describe the solution you'd like**

Contour log verbosity should be configurable, so debug logs can be turned off by default.

**Anything else you would like to add:**

Contour outputs debug logs from `internal/grpc/xds.go:xdsHandler.stream` main loop by default, which may be quite verbose (in a small cluster with around 20 ingresses objects I've noticed around 400 lines every couple of seconds).

In an attempt to solve this, I've opened #1131, which is now closed so we can discuss the preferred approach here. The mentioned PR adds the flag `--log-level`, which defaults to `info`, and sets the `internal/grpc/xds.go:xdsHandler.stream` main loop logs to `log.Debug`, reducing the amount of logs for each loop. The old behavior can be restored by setting `--log-level=debug` on Contour startup.

Example logs (note that I've omitted real ingress names):

```
time="2019-05-29T22:49:04Z" level=info msg=response connection=23 context=grpc count=1 error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=stream_wait connection=23 context=grpc error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=response connection=11 context=grpc count=1 error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=stream_wait connection=11 context=grpc error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=response connection=15 context=grpc count=1 error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=stream_wait connection=15 context=grpc error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=response connection=9 context=grpc count=1 error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=stream_wait connection=9 context=grpc error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=response connection=6 context=grpc count=1 error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-29T22:49:04Z" level=info msg=stream_wait connection=6 context=grpc error_detail=nil resource_names="[omitted]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
```

**Comment by davecheney** [comment]
Thank you for raising this issue. I'm sorry in advance for the length of this reply, it is in part a recitation of my blog post on logging; https://dave.cheney.net/2015/11/05/lets-talk-about-logging

Fundamentally I believe that log lines should be written to be read. If log lines are emitted and are not useful they should not be emitted in the first place. This is hopefully not a controversial statement. 

The problem is a switch that chooses which lines to emit. I don't want to add a debug mode which suppresses some or all of the lines because that will mean when troubleshooting operators will have to change the log level and try to recreate the problem. What I would like to do is talk about a way that the output from the logging loop in `internal/contour/xds.go` can be trimmed down so that it only emits information which is germane to the operator. I don't what that would look like but I am happy to discuss this here.

**Comment by stevesloka** [comment]
It's a long shot, but #1251 **might** be related.
