### ISSUE TITLE
internal/dag: Ingress spec.rules.host should reject values with a *

### ISSUE THREAD

**Issue by odacremolbap** [heptio/contour#1234]
**Describe the solution you'd like**

Add validation to avoid processing `Ingress` objects whose FQDN contain wildcarded domains.

Related to https://github.com/heptio/contour/issues/1167
See https://github.com/heptio/contour/pull/1227#issuecomment-509112757

**Motivation**
Match `Ingress` behaviour with `IngressRoute` objects where domains including `*` are incompatible with [delegation](https://github.com/heptio/contour/blob/master/docs/ingressroute.md#ingressroute-delegation), and should be rejected 

**Concerns**
- While `IngressRoute` is a CRD and is being validated as such, `Ingress` is an _upstream object_, probably can only be validated using an Admission Controller, which sounds very out of bounds.
- Afaik delegation is not possible with `Ingress`, theoretically there shouldn't be any problem allowing wildcarded FQDN unless there are further plans to allow `Ingress` to be part of delegation. 
- `Ingress` and `IngressRoute` as expected use the same [Vertex map](https://github.com/heptio/contour/blob/374d846f3ebcb1b6693af95835753830181da52a/internal/dag/builder.go#L204). This means that `Ingress` routes can get in the way of `IngressRoute` without the internal validation that the later is undergoing. Not only `Ingress` wildcards could wreak havoc at `IngressRoute` delegation, but (pending closer inspection of the code) I think anyone could bypass a delegated domain using an `Ingress` that uses the delegated domain.

**Environment:**

- Contour version: 0.13.0
- Kubernetes version: 1.14

**Comment by stevesloka** [comment]
@odacremolbap thanks for raising this! Yes, I think you can create some interesting scenario's when combining `Ingress` with `IngressRoute`. I just opened an [issue](#1241 ) to also track disabling `Ingress` when `IngressRoutes` are used. I think this should be another step in forcing users into delegation in specific scenario's (mainly multi-team, or when more validation is requested). This also, however, is a good step in any case.

**Comment by odacremolbap** [comment]
I'm ok working on this if I can be assigned.

**Comment by stevesloka** [comment]
Before you go too far @odacremolbap I'm curious what @davecheney thinks about this. One goal of Contour is to still fully support the upstream spec (e.g. ingress/v1beta1). Thinking about this a bit more since my last post (37 minutes ago), I'm wondering how much we should limit the functionality of Ingress for users to want to continue to use that route.

**Comment by odacremolbap** [comment]
sure!

I was about to answer to the [issue you just opened](https://github.com/heptio/contour/issues/1241), posting here:

Is a _domain validator_ discarded?
- Validating domains for both `Ingress` and `IngressRoutes`, and rejecting overlapping ones sounds like a simple solution to always allow both (no need for #1241)

- Same goes with wildcards, could be allowed as long as there is no existing delegation scenario that could be affected, an vice-versa, before creating a delegating `IngressRoute` existing domains should be checked (no need for implementing this one nor merging #1227) 

Not sure if you might be already working on [something related](https://github.com/heptio/contour/issues/1228#issuecomment-510568698).

**Comment by davecheney** [comment]
Envoy treats domains with the name "*" specially. We _must not_ allow the string "*" to be entered into ingress.spec.host because that behaviour is not defined in the k8s ingress spec -> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#ingressrule-v1beta1-extensions

Specifically there is no agreement in the k8s spec what a `host: *` value means. nginx interprets it one way, Envoy interprets it another. The k8s spec says 

> Host is the fully qualified domain name of a network host, as defined by RFC 3986.

Which means "*" is not a valid string. This ticket is to ensure that Contour rejects this invalid string when it is present in k8s ingress host rules.
