### ISSUE TITLE
cmd/contour: hook SIGHUP to gracefully shut down contour serve

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1364]
`contour serve` runs until one of the members of `serve`'s workgroup exits, shutting down the rest of the group.

For testing we sometimes manually hack in poison pill style jobs which terminate the group after a period of time #1361. It would be useful to be able to a graceful server shutdown rather than ^C the process. I propose we hook up SIGHUP to terminate the group.

**Comment by alexbrand** [comment]
+1. This would also allow graceful shutdown by the Kubelet when terminating contour pods.

**Comment by alexbrand** [comment]
I'd love to pick this up. I've got a couple of questions:

- Kubernetes sends a SIGTERM and not a SIGHUP when terminating a pod. I was thinking we could hook up SIGTERM instead of SIGHUP. Thoughts?

- Is a new goroutine in the Workgroup the right place for implementing this? I am thinking `g.Add` a new goroutine in `serve.go` that setups the signal handler and blocks on the notification channel. Once the signal is handled, the goroutine logs and returns nil.

**Comment by davecheney** [comment]
@youngnick any objections to SIGTERM?

**Comment by youngnick** [comment]
No objections to SIGTERM, particularly since we're shutting the program down as the response anyway. Probably better not to overload SIGHUP (which has the expected behaviour of leaving the program running) anyway.

Good idea.

**Comment by davecheney** [comment]
@alexbrand all yours next week once we start the next cycle.

**Comment by davecheney** [comment]
> Is a new goroutine in the Workgroup the right place for implementing this? I am thinking g.Add a new goroutine in serve.go that setups the signal handler and blocks on the notification channel. Once the signal is handled, the goroutine logs and returns nil.

Yup. That's a good plan.
