### ISSUE TITLE
[Feature Request] Ability to configure which ingressClass Contour watch

### ISSUE THREAD

**Issue by Nikkau** [heptio/contour#255]
Hi,

Today the check for IngressClass annotation is against a hardcoded value (https://github.com/heptio/contour/blob/master/internal/contour/translator.go#L143-L144).

Are you open to make it configurable?
I use k8s on GKE and I expose ingresses both public and privately with external and internal LBs, I plan to use this annotation to "map" my services on the right side of my cluster.

Btw, great work, Contour is dope 👍 .

**Comment by davecheney** [comment]
I think this is a reasonable request and would help with tools like kube-lego which are kind of hard coded to only understand "gce" or "nginx". 

I'm going to mark this has help wanted as I'm not planning on working on this for 0.4.

If you want to contribute to this feature, please discuss the change you plan to make, and how you will test it here on this issue _before_ coding. If you send a PR without discussing the change I will close it and redirect you here to discuss your change first. Sorry, them's the rules.

**Comment by Nikkau** [comment]
I'm not very familiar with the code base yet, my initial naive plan is:
- Add a "ingress class name" field on Translator struct.
- Add a flag in `main()` to choose a name.
- Update `addIngress()` to compare annotation against this field or "contour" in case of nil value.

For testing, I think I have to add a new test which is like `TestTranslatorAddIngress` with a `Translator` created with a value for Ingress name.

**Comment by Nikkau** [comment]
After trying these ideas a bit, I think interpreting the nil value as `"contour"` is painful, it forces ugly checks to do the job.

My new proposal is to add constant for the default value ("contour") and set this new field with this default value everywhere a Translator is created (seems smelly but it's already did for the `log` field) except the new test specially crafted for this feature.

**Comment by davecheney** [comment]
@Nikkau sounds good to me

For creating the default, have a look at the pattern in cmd/contour

https://github.com/heptio/contour/blob/master/cmd/contour/contour.go#L72

To get a `t.IngressClass` field, add it too

https://github.com/heptio/contour/blob/master/internal/contour/translator.go#L48

following the pattern here

https://github.com/heptio/contour/blob/master/internal/contour/listener.go#L43

and then add a small private getter to fill in the default `"contour"` if the field isn't set

https://github.com/heptio/contour/blob/master/internal/contour/listener.go#L127

For testing, i'd start by copying this test case into a new test

https://github.com/heptio/contour/blob/master/internal/contour/translator_test.go#L509

You'll want to _always_ provide a translator, rather than letting the test harness provide one; something like

```
tests := map[string]struct {
        tr *Translator
        ing *v1beta1.Ingress
	ingress_http  []route.VirtualHost
	ingress_https []route.VirtualHost
} { 
    // test cases
}

for name, tc := range tests {
    t.Run(name, func(t *testing.T) {
          t.OnAdd(tc.ing)
          // check ingress_http and ingress_https match tc.ingress_http, ingress_https
   })
}

**Comment by Nikkau** [comment]
I just submitted #256.

For reference, my first try was https://github.com/Nikkau/contour/commit/6503421e8176c07099ea75dbe572513cff3b5d04 which save the call to `ingressClass()` at each `{add,remove}Ingress()` invocation but it clearly doesn't happen often enough to be a useful optimization.
