### ISSUE TITLE
Add a FAQ to address common questions

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#26]
Maybe we should add a FAQ document to address common questions such as a the difference between contour and istio.

**Comment by Bradamant3** [comment]
I'm not a huge fan of FAQs because most of the time they either compete with the core docs in confusing ways, or they're lazy shortcuts to avoid dealing properly with docs, or they're more marketing than anything else bc "people expect them."

But if we have a real set of Qs whose answers don't belong anywhere else, then OK.

**Comment by davecheney** [comment]
This is addressed in #28. I’m going to close this, we can open future bugs for specific things that need to be called out.
