### ISSUE TITLE
Enable websocket support?

### ISSUE THREAD

**Issue by azuretek** [heptio/contour#289]
I'm trying to get websockets working but it looks like it's not enabled. When I try to upgrade to a websocket connection I get ssl handshake errors currently.

The envoy docs indicate we should be able to enable it like so:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#envoy-api-field-route-routeaction-use-websocket

Nginx handles websocket endpoints like this:
https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket

**Comment by glerchundi** [comment]
In [`nginx-ingress`](https://github.com/kubernetes/ingress-nginx/blob/nginx-0.12.0/rootfs/etc/nginx/template/nginx.tmpl#L881-L882) it's available by default and then you probably need to tweak `proxy-{read,write}-timeout` in order to keep it really persistent.

@davecheney I can submit a PR once you validate the how.

Proposals:
* Always on. Need to check which are the default `read`/`send` timeout values.
* Configurable through annotations, which annotation?
  * NGINX Inc. ingress uses `nginx.org/websocket-services: "service1[,service2,...]"`
  * Kubernetes ingress uses nothing because it's always-on but most of the times websocket ping frequency is greater than 60s (which is the default for `read`/`send` timeouts) which required the use of `ingress.kubernetes.io/proxy-read-timeout` & `ingress.kubernetes.io/proxy-send-timeout` in order to avoid socket from being closed.

**Comment by davecheney** [comment]
I'm not sure the nginx method is correct. As I understand it, websocketness is a property of the route; ie /ws, not the backend service. 

If anything this should be

a. `contour.heptio.com/websocket-routes: "/route1,[route2,...]"` on the ingress
b. `contour.heptio.com/upstream-protocol.ws: "port,[port]"` on the service.

**Comment by glerchundi** [comment]
> I'm not sure the nginx method is correct. As I understand it, websocketness is a property of the route; ie /ws, not the backend service.

Yes.

> If anything this should be
> 
> a. contour.heptio.com/websocket-routes: "/route1,[route2,...]" on the ingress
> b. contour.heptio.com/upstream-protocol.ws: "port,[port]" on the service.

AFAIK the second one is not needed at all. Envoy works in the same way other proxies do, forwards the upgrade (in case it exists) to the upstream and this should follow the ws handshaking: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/websocket

Will send a PR.

**Comment by rosskukulinski** [comment]
Hi @marcoskichel - Websockets have been enabled for the new IngressRoute CRD that is part of the upcoming 0.6.0 release.  Documentation can be found here: https://github.com/heptio/contour/blob/master/docs/ingressroute.md#websocket-support

If you'd like to test one of the beta releases, you can update your Contour image to `gcr.io/heptio-images/contour:v0.6.0-beta.2`

**Comment by marcoskichel** [comment]
Thank you!
