### ISSUE TITLE
Customizing Envoy through Ingress resources

### ISSUE THREAD

**Issue by kyessenov** [heptio/contour#29]
Envoy provides a collection of features that are beyond host/URI routing formalized in the Ingress resources (advanced load balancing, fault injection, custom filters, etc). Do you have any plans or thoughts how to expose those features in the ingress controller?

**Comment by davecheney** [comment]
Thanks for your issue. At the moment, probably not because the means to do so don't exist in the Ingress object.

Conceivably this could be done with annotations on the Ingress or Service object, but there is some concern that ad hoc growth of annotations is a bit of a hack.

This could probably also be done via ConfigMaps to provide more structured configuration that could be mixed into the configuration served up to Envoy. But, at this stage, it's probably outside the remit of Contour to be a straight forward Ingress controller.

**Comment by davecheney** [comment]
I'm going to close this question as answered. If you have further questions feel free to open a new issue, or [try one of the other support options][0]

Thanks

Dave

[0]: https://github.com/heptio/contour/blob/master/SUPPORT.md

**Comment by phylake** [comment]
What does this look like now that IngressRoute is here? I'm looking for generic envoy filter config to be passed down in a similar fashion as [Istio](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#EnvoyFilter)
