### ISSUE TITLE
Ingress class processing

### ISSUE THREAD

**Issue by Lookyan** [heptio/contour#297]
I'm not sure whether it's right behavior or not:

For now, we have this logic to determine if we need to create a route in envoy or not:
https://github.com/heptio/contour/blob/master/internal/contour/translator.go#L156-L174

But this logic gives us all ingress resources which don't have ingress class annotation. Is it right or wrong? Maybe we need to filter such ingress resources?

Also, is it ok to start contour ingress controller with same ingress class as default nginx ingress controller? Will it break smth in ingress resources in kubernetes cluster?

**Comment by davecheney** [comment]
> But this logic gives us all ingress resources which don't have ingress class annotation. 

Correct, if you don't list an ingress class, your ingress may be served by multiple ingress controllers.

> Is it right or wrong? 

I think it's a fine default, it would be sure confusing to deploy an ingress object and it do nothing because it wasn't served by an ingress controller

> Maybe we need to filter such ingress resources?

I don't think so. Do you have an example where this behaviour is bad?

> Also, is it ok to start contour ingress controller with same ingress class as default nginx ingress controller? 

As in, `contour serve --ingress-class=nginx` while the nginx controller is running? 

> Will it break smth in ingress resources in kubernetes cluster?

At the moment, nothing bad will happen, but that probably won't be true in the future once #21

**Comment by Lookyan** [comment]
Ok, now it's clear, thank you. I think it's right behaviour.
