### ISSUE TITLE
Feature request: External-DNS integration

### ISSUE THREAD

**Issue by lypht** [heptio/contour#307]
Integration with https://github.com/kubernetes-incubator/external-dns would allow for a user to generate an ingress and eliminate manual manipulation of DNS records separately.

**Comment by lypht** [comment]
Just noted that `Support for Services with type=NodePort` is listed in the `external-dns` _Yet to be Defined_ section: https://github.com/kubernetes-incubator/external-dns#yet-to-be-defined

**Comment by davecheney** [comment]
Thank you for raising this issue. I think this is a good proposal, but it is outside the remit of Contour -- we just do http. For example, Contour interacts with the lets encrypt ecosystem via the ingress api and tools like cert-manager, which keeps their concerns separated. I see this as the same situation here, another tool should concern itself with updating DNS entries to point to the service loadbalancer of the the ingress controller.

In the spirit of transparency, rather than letting this rot in our issue tracker I am going to close this issue. Please understand that I do not mean to imply that this suggestion is bad, it is just outside the scope of Contour.
