### ISSUE TITLE
Contour does not correctly/consistently processes updates to services weights

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#581]
Remaining work:

- [X] Support duplicate Service usage with different weights [Fixed in #635]
- [x] Support duplicate Service usage with different strategies
- [ ] Support duplicate Service usage with different health check properties

---

It's possible to reference a single Service multiple times in a single IngressRoute, each with a different LoadBalancer Strategy, HealthCheck, or Weight.  Similarly, multiple IngressRoutes can reference a single Service with differing strategy, healthcheck, or weight.

The result is appears to be non-deterministic -- often times the resulting Envoy configuration for a any given route is 0% weight, or disabling the health check, depending on which Service reference was used to compute the CDS cluster from the DAG.

The Contour team has discussed three courses of action for this situation:

1) Mark all IngressRoutes that use a Service multiple times as Invalid (and update the `status` field)
2) Create a CDS cluster for every Service that's used in an ingressroute, thus resulting in always accurate route configuration, but duplicate CDS clusters
3) Create a CDS cluster for each unique Service that uses in an ingressroute.

From a end-user PoV, the current behavior and option (1) provide a terrible user experience.  Re-using a Service multiple times seems to be a common scenario, and sending traffic to /dev/null is not good.

As for (2) or (3), I think either option works for end-users. 

One thing to keep in mind, is that the `cluster-name` field is used in the Gimbal metrics/monitoring system.  Currently the name is `${namespace}/${servicename}/${port}`. I think we would want to append or prepend the name of the IngressRoute and/or Path referencing this Service, and be sure to update our metrics regex.

**Comment by rosskukulinski** [comment]
@davecheney PTAL for your thoughts before vacation.  @stevesloka has offered to dig into the issue, but I think he wanted to hear your thoughts on (2) vs (3) and/or other ideas.

**Comment by davecheney** [comment]
I won't be able to work on this for a few days, but I wanted to write down my thinking on how to approach this issue, both for my recollection, and anyone else who is watching this issue.

Currently ingressroute objects specify things like health checks, load balancer config, timeouts, etc on the `spec.path` key. So those attributes are properties of the _route to a service_, not the _service itself_. However on Envoy's side, those same properties are configured on the Cluster object in CDS--that is to say, they are properties of the Cluster (the k8s service) not the route to the service. 

This bug arises from two conditions; on in `dag.Builder.Compute` the other in the way the link between RDS, CDS and EDS entries are done via string matching.

## `dag.Builder.Compute`

The first issue is during `dag.Builder.Compute` we build sets of Service objects (which will be translated into Envoy Clusters 1:1 by `contour.ClusterVisitor`) using their name, namespace and port as the identifying tuple. Because load balancer, timeout, health check, etc are not part of this key during computation of a DAG its ambiguous if a route is being connected to a new service object, or an existing one, so the health check, et al, properties which are translated from the ingressroute route object to the dag.Service object may overwrite existing settings. See Issue #503 for a discussion that those properties probably belong on the Service object. 

The net result is during processing if you have two routes which mention the same service name/namespace/port tuple with different health check params, etc, the results are undefined and will likely nutate between all states in rapid secession.

The solution to this problem I believe is to recognise that a service named by routes with different hc/timeout/etc params is actually a different service--we need to extend the definition of equality beyond hc/timeout/etc params. This is logically straight forward to do, but leads to two issues described in the next section

## RDS, CDS and EDS entry string matching

The linkage between RDS, CDS and EDS is stringly typed. RDS mentions by name a CDS cluster, and CDS mentions by service name and EDS entry containing its endpoints. Some of this names are controlled by us, others are generated blindly. 

Specifically the CDS name we provide RDS is a 60 character string, this must identify to RDS the cluster we mean. We currently use the format `namespace/name/port` and truncate, git short hash style. 

The linkage between CDS and EDS is done in the blind, the EDS grpc service derives the name of EDS clusters from the Endpoint document, and only has access to the namespace, name, and port (named or unnamed) of the service. There is no restriction for the length of this string, so we use the `namespace/name/port` convention without truncation. This name is supplied to CDS using the [eds_config.service_name](https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v2/cds.proto#envoy-api-msg-cluster-edsclusterconfig) field which allows us to provide an alternative name for the EDS members of a cluster -- they don't have to match the truncated 60 char name of the CDS clusters.

With this said the information about the hc/timeout/etc states needs to be encoded into the name of a CDS cluster -- different clusters (see the definition of equality above) require different CDS entries. Inside the dag.Builder the definition of equality will always include the full set of heath check/timeout/lb details, but how we choose to represent it in the Clusters' name is up to us.

This representation should be stable; so that rules out names like `namespace/name/port/sequence` as the sequence number order is undefined and will cause a lot of churn on the Envoy side as the entire CDS configuration shifts on each update -- it will also be hard to write reliable test fixtures if the sequence numbers are not predictable ahead of time.

Instead we could include all the parameters we want in the name `namespace/name/port/lbstrategy/hcparam1/hcparam2/etc`. This has some problems due to the 60 char limitation, even cherry picking the parameters we want to identify the difference between related services we're doing to eat up our 60char budget and either be unable to represent the name uniquely, or the name will be so mangled there is no value in trying to keep it human readable over simply using a hash.

The third option, one that I am proposing is something like `namespace/name/port/hash` where hash is a hash (probably sha1) of the full set of hc/lbstrat/timeout/` params encoded as a string. This gives us a fighting chance of having readable service names where the operator can tell where two clusters are related, but differ in connection type parameters, e.g. `default/httpbin/8080/e6d3f7g` and `default/httpbin/8080/7e339a2b`

**Important** This only applies to the Cluster.Name and RDS.Cluster.Name fields, Cluster.ServiceName is unaffected and will remain `namespace/name/port` (untruncated) as this is required to match the value that EDS generates in the blind. There are several open questions for investigation to see if Envoy will permit an ClusterLoadAssignemnt entry (from EDS) to be present in multiple clusters, but assuming this is possible, there should be no problem with the same Endpoints (from the k8s endpoints document) being present in several Envoy Clusters representing the same k8s Service with different healthcheck,timeout, and load balancing strategies.

Open questions:

- [ ] can an EDS endpoint be part of multiple CDS clusters?
- [ ] can we list the same ServiceName in server CDS entries?

**Comment by rosskukulinski** [comment]
Pulling in details from #514 so it can be marked as dup:

Load balancing strategies and health checks should also be allowed to be different.

**Comment by davecheney** [comment]
Moving to 0.6 final

**Comment by rosskukulinski** [comment]
Updated issue description with checklist of remaining end-user changes.
