### ISSUE TITLE
IngressRoute gauge metrics not being cleared

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#612]
Contour outputs a few `gauge` type Prometheus metrics related to IngressRoutes.  Namely:

* contour_ingressroute_invalid_total
* contour_ingressroute_valid_total
* contour_ingressroute_orphaned_total
* contour_ingressroute_total

Due to the nature of the Prometheus library, once a gauge metric is set, it will remain at that value until changed.  Currently we do NOT set these metrics to 0 if a corresponding ingressroute is removed (or changes state from valid->invalid, invalid->valid, orphaned->valid, orphaned->invalid, invalid->orphaned, valid->orphaned).

This results in misleading graphs (like the Gimbal `Valid IngressRoutes` graph), showing old Virtualhosts that no longer exist.

We should set gauges to 0 if the corresponding ingressroute or virtualhost or namespace is gone.  If possible, we should also delete the gauge from Prometheus (if that's possible - it may _not_ be).

**Comment by stevesloka** [comment]
I've been working on this today and I think I have a solution. The problem with how metrics are implemented today is that they only represent the current state of metrics since that's how the DAG is built. However, when the statuses change (e.g. from an orphan status to valid) there's no trigger to update the metrics appropriately and we get bad metrics. 

I think we need to keep a local cache of the metrics that have been written in the `metrics` package. This way on a new update, we can compare the new set of metrics against what existed previously and update according to what changed. 

This also works on a cold startup because no metrics exist until the first DAG is computed, so if Contour was down during changes, then there are no data inconsistency issues.
