### ISSUE TITLE
internal/generated: Allow users to consume IngressRoute client

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#704]
**Describe the solution you'd like**

Users who want to write controllers for their clusters which manipulate `IngressRoute` objects should be able to re-use the internal client Contour uses. Right now they cannot because the generated client exists within the `internal` package of Contour. 

Also, users should not have to depend on all the entire Contour repo as a dependency. One possible solution would be to move the generated client as well as the API spec to a new repo. 

This is a result of a Slack conversation with @amoskyler.

**Comment by davecheney** [comment]
I agree! We should do this.

The only question I have is should we _just_ export our IngressRoute types, or should we combine them with the others from ark and sonobuoy.

**Comment by davecheney** [comment]
Here's what I think we should do for 0.7 -- we can continue to iterate on it later if it turns out to be the wrong choice.

For 0.7 let's move the client out of internal/. If there are some good patterns we can follow from other projects I'll keep my curmudgeonly views on package naming to myself for the duration :P
