### ISSUE TITLE
IngressRoute design: represent envoy directly

### ISSUE THREAD

**Issue by phylake** [heptio/contour#857]
**Describe the solution you'd like**
I'd like envoy to be represented 1:1 in IngressRoute. 

**Anything else you would like to add:**
Main advantages
1. You could [link to envoy's excellent documentation directly](https://www.envoyproxy.io/docs/envoy/v1.9.0/intro/arch_overview/load_balancing/load_balancers), instead of [re-documenting](https://github.com/heptio/contour/blob/v0.8.1/docs/ingressroute.md#load-balancing-strategy) parts of envoy as they're represented in Contour.
1. Contour could leverage [protobuf-generated Go](https://github.com/envoyproxy/go-control-plane/blob/v0.6.1/envoy/api/v2/route/route.pb.go) (notice the `json` tags already present on each field) and [validation](https://github.com/envoyproxy/go-control-plane/blob/v0.6.1/envoy/api/v2/route/route.pb.validate.go) instead of going through unwieldy translation layers. The following links illustrate this with websockets: [IngressRoute's `EnableWebsockets bool`](https://github.com/heptio/contour/blob/v0.8.1/apis/contour/v1beta1/ingressroute.go#L62) [is assigned to](https://github.com/heptio/contour/blob/v0.8.1/internal/dag/builder.go#L623) [dag.Route's `Websocket bool`](https://github.com/heptio/contour/blob/v0.8.1/internal/dag/dag.go#L62) which is finally [assigned to](https://github.com/heptio/contour/blob/v0.8.1/internal/envoy/route.go#L31) the (protobuf-generated) [RouteAction's `UseWebsocket`](https://github.com/envoyproxy/go-control-plane/blob/v0.6.1/envoy/api/v2/route/route.pb.go#L1423) that's passed to envoy. That's 3 names for the same boolean. If the RouteAction struct was deserialized directly there would be no translation. Admittedly, I don't know how the DAG would be impacted but I'd be happy to work through it. The cognitive, lines of code, and testing overhead of this translation can't be overstated.
1. If you could do 2. then adding the many features requested (I believe that would minimally cover #805, #608, #437, #361, #70, #69, and #515 which were all open as of this writing) would be trivial, or even automatic as new fields are added to the protobufs
1. The CRD could be generated automatically
1. The CRD could be versioned to match envoy versions. There would be no version matrix or backward compatibility to deal with.

My biggest question: is a goal of Contour to abstract envoy?
- If the answer is no, then I'm not sure why this wasn't the approach taken in the first place once a CRD was on the table.
- If the answer is yes, then I think you need to change the project's description: "Contour is a Kubernetes ingress controller for Lyft's Envoy proxy."

Are there any challenges besides representing the DAG that I'm missing? I'd much rather tackle this problem than repeat #856 for every bit of config in envoy that we need.

**Environment:**
N/A

**Comment by davecheney** [comment]
@phylake thanks for raising this issue. In answer to your question

> My biggest question: is a goal of Contour to abstract envoy?

The answer is _yes_. It's probably never been explicitly stated, but the goal of Contour is to provide an opinionated deployment of Envoy as a HTTP reverse load balancer. There are many things that Envoy can do, the goal of Contour is _not_ to expose all of those to end users.

With that said I want to give your proposal close thought. It does seem redundant to reimplement the envoy data structures as a CRD, but I offer the following mitigating concerns.

1. envoy's data structures change _a lot_. To some extend Contour hides this churn which is a good thing.
2. the envoy grpc api is very complex and provides no opinions. In some way Contour is an opinionated shim over the envoy api. Interacting with envoy via gRPC types gives you some guard rails via compiler errors, navigating the complex API via k8s yaml would be a frustrating experience.

wrt to the project description, do you have any alternative suggestions?

**Comment by stevesloka** [comment]
Another goal of ingress route was to not tie it to envoy, others could implement the CRD and not use Envoy.

**Comment by phylake** [comment]
Thanks for the clarification @davecheney and @stevesloka. I think it would be good to call out the project's goals somewhere.

> envoy's data structures change _a lot_. To some extend Contour hides this churn which is a good thing.

Do you agree there's a tradeoff here? That hiding Envoy's churn slows down contour development?

> navigating the complex API via k8s yaml would be a frustrating experience

It couldn't be more frustrating than configuring Envoy directly which isn't frustrating and is really what I'm asking for. While the many open feature requests may not be asking for it directly (i.e. the requestors may not care "how" the feature's exposed) I don't know that they'd be frustrated by having all of envoy's features available to them. Have you asked them? That said I recognize it goes against the goal of not tying the CRD to envoy.

> wrt to the project description, do you have any alternative suggestions?

I think it's worth adding "opinionated" to the description and elaborate on the opinions somewhere. That'll be important to people evaluating ingress controllers. I'd like to know what the opinions are too.

> The answer is _yes_
> ...
> Another goal of ingress route was to not tie it to envoy

I think your abstraction is leaking. You've already exposed the exact [Load Balancing Strategies](https://github.com/heptio/contour/blob/c339b3a2cdd11cb0c6030ff77a80380770309539/docs/ingressroute.md#load-balancing-strategy) in envoy. This is [indirection, not abstraction](https://zedshaw.com/archive/indirection-is-not-abstraction/). HAProxy and Nginx (as examples of other reverse proxies you might tie envoy to) don't have MagLev afaik.

The CRD structurally matches Envoy's [Route](https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/route/route.proto#route-route), [RouteAction](https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction), and [WeightedCluster](https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/route/route.proto#envoy-api-msg-route-weightedcluster)

A third example will be #856 if you merge it.

I'm being critical, not malicious, btw :)

My final thought on the goal of not tying IngressRoute to Envoy: If others are like me, they know which proxy they want to use and look for an ingress controller for it, not the other way around. I don't _want_ or _need_ the abstraction because I don't _want_ to have to figure out how the CRD maps to Envoy config, and I don't _need_ to swap out the underlying proxy

**Comment by unicell** [comment]
@phylake I'm also facing the similar issue. The route I'm currently taking is to extend IngressRoute CRD with some new protobuf defined fields. And those protos could either be defined within the project, or use the one from Envoy dataplan-api. For the latter one, it becomes a one to one mapping to what Envoy can be configured through xDS.

I found this approach provides the benefits from both sides, manageable in-house changes and yet not too intrusive for Contour code base. Wondering if I can contribute it back somehow.

**Comment by bgagnon** [comment]
Relevant info from the Envoy project:
* envoyproxy/envoy#6271
* [Breaking Change Policy](https://github.com/envoyproxy/envoy/blob/master//CONTRIBUTING.md#breaking-change-policy)
* [xDS Protocol Versioning](https://docs.google.com/document/d/1nAomWSjvSSFCNZ1wQJ7D01f5VGDGLn5zcNxcDozYqYI/edit?usp=sharing)

From the documents above, I gather that:
* the Envoy community is very much aware of API breakage issues
* there are concrete plans to address this
* there are concerns this will slow down velocity on Envoy

Since it's not a completely solved problem on the Envoy side, I sympathize with Contour's desire to shield the end user from this churn. As things mature and stabilize, however, I have to agree that the double translation between Envoy and Contour leads to undesirable things illustrated by @phylake :
* leaky abstractions
* redundant structures and aliasing
* cognitive overhead in the translation of concepts and configurations

Moreover, I see a pattern of re-assessing the value of each Envoy feature from the Contour side (ex: cors, auth, sticky sessions) and re-having the debate on how things should be named and configured and if they are out of scope or not for this project.

The one thing I have a hard time wrapping my head around is the idea that the IngressRoute CRD should be abstracted enough to work with other proxies, and perhaps one day graduate from not being a CRD anymore and moving to K8S core API itself.

In my experience, the native Ingress resource clearly demonstrated this was really hard and ultimately resulted in highly specialized annotations that basically render the average non-trivial Ingress object in the wild entirely proxy-specific.

This led to the proliferation of CRDs in all modern takes on ingress controllers, and the resulting objects and documentation have been a lot more sane than the decorated native objects. I for one don't see a reason for someone starting out to use Ingress with Contour; I would go directly for IngressRoute. I have the same preference for CRDs with Istio, Gloo, Ambassador and Voyager.

Perhaps the only redeeming  quality of the native Ingress is that it can be dropped in a Helm chart with _some_ confidence that it _might_ just work for the receiving user without modification. And maybe that is what Contour is hoping for with IngressRoute.

In any case, I will be watching this "fork in the road" issue closely.

**Comment by davecheney** [comment]
Hello,

Thank you for the discussion on this issue. This issue has been open for a long time without comment. I apologise for that. My workload is immense.

I appreciate that it is frustrating to have to wait for Contour to add its own translations of Envoy concepts, and I hope that this will improve in the future as the team hopefully grows, but this isn't a good justification to just drop the Envoy gRPC api on k8s users wanting a HTTP ingress solution. By exposing the full verbosity of Envoy's gRPC we provide no guidance, no defaults, no opinion to help our users get started, no option to improve their experience other than pushing them towards a templating solution.

We will not expose Envoy's data structures directly to the k8s API. This is a design decision based on Contour's desire to focus on web applications, not be a generic service proxy. There are other projects that want to be generic service proxies, we have no interest in competing with them.
