### ISSUE TITLE
Contour support for Web Application Firewall (WAF)

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#893]
**Describe the solution you'd like**

As a platform operator, I would like to be able to configure Contour/Envoy to provide Web Application Firewall capabilities.

Web Application Firewalls, like the popular open source [ModeSecurity](https://modsecurity.org/) WF are used to detect and stop a broad range of Layer 7 attacks and block traffic from known malicious IP addresses:

* SQL injection (SQLi), cross‑site scripting (XSS), and Local File Include (LFI), which which together account for over 90% of known Layer 7 attacks
* Cross‑site request forgery (CSRF), Remote File Include (RFI), remote code execution (RCE), and HTTP protocol violations
* Other common attack vectors, detected by custom regex‑based rules

**Anything else you would like to add:**

Envoy does not natively enable this capability, so the feature would need to be added upstream or a custom build of Envoy could be created using [ModSecurity-Envoy Filter](https://github.com/octarinesec/ModSecurity-envoy).

Alternatively, it sounds like we could integrate through the envoy.ext_authz Filter: https://groups.google.com/forum/#!topic/istio-users/ThF36PMJKqs.  This might be the preferred integration point, but we might want to create another sub/sibling projects to package ModSecurity to be used in that fashion.

**Comment by yob** [comment]
I would be interested in this, even if it was fairly basic.

In a past life we often used [fail2ban](https://www.fail2ban.org/wiki/index.php/Main_Page) to block obviously malicious clients (like anyone repeatedly requesting `/wp-admin/login.php` when we don't use wordpress). It was based on regexps, and something similar in contour would be super helpful.

**Comment by davecheney** [comment]
I am going to close this issue because we do not plan to ship a custom Envoy and it looks like the 3rd party filter has not been updated for close to a year. Without this feature available in mainstream envoy we cannot offer it in Contour.

Please feel free to reopen this issue if this feature lands in envoy.

**Comment by Josh-West-Bose** [comment]
:-(

**Comment by davecheney** [comment]
I’m sorry to disappoint you. The facts are were not going to get into the business of shipping a custom version of envoy. This is in part because we don’t have the cycles to take on the maintainence of what would equate to a fork of envoy. Also, this would put VMware in the position of shipping envoy which has impacts on our ability to ship Contour to us embargoed countries. This is simple something a small project can tackle. 

In light of that, without the features we need upstream, we cannot fullfil this feature request so the most honest thing to do is to close the issue.
