### ISSUE TITLE
Implement Secret Discovery Service 

### ISSUE THREAD

**Issue by vaamarnath** [heptio/contour#898]
Implement Secret Discovery Service in Contour.

This enhancement request came out of the discussion on #862 for supporting rotating and invalidating certificates using SDS. More info about SDS is available here: https://www.envoyproxy.io/docs/envoy/latest/configuration/secret.

**Comment by khgandhi** [comment]
@vaamarnath we have a requirement to have SDS implementation in contour as well. Do you have a design that you can share with the details ?

**Comment by vaamarnath** [comment]
@khgandhi The current requirement for SDS came in through #862. There is no design available for this issue at this point in time. 

\cc @davecheney

**Comment by bmadhavan** [comment]
@davecheney If you are ok, I can pick up this task. I can come up with a rough design doc and a list of possible changes in a couple of days.

**Comment by davecheney** [comment]
@bmadhavan sure, feel free to discuss the design here or in a design document. Please note that I will be travelling until the 1st of April and may not be able to reply during that time.

**Comment by bmadhavan** [comment]
ok. Sure.

**Comment by bmadhavan** [comment]
@davecheney I have created an initial design draft for SDS support. Can you please take a look.

**Comment by davecheney** [comment]
Due to the need to ship Contour 0.11 to address a security issue in Envoy 1.9.0 this has been bumped to the 0.12 milestone.

**Comment by davecheney** [comment]
With #901 falling off the 0.12 milestone @vaamarnath and I have talked and the plan is to implement the basic SDS plumbing and we'll revisit the integration points with the rest of Contour later. 

I was going to sit down and write down the steps to add SDS to `internal/grpc` but it turns out we already have 99% of the design from @bmadhavan in #960. I've polished that up and you can find [here](https://github.com/heptio/contour/blob/master/design/sds-design.md).

I'm not going to mark this issue as 0.12 as @vaamarnath nor I can commit to taking this one by the 0.12 deadline, but consider the design for adding SDS up for grabs. 

Note to implementors: please work incrementally, one PR per high level design point. Please don't send one giant ass PR for the whole thing, that's not cool. You should also add some tests to `internal/e2e` which are really the func tests of `internal/grpc`.

Thanks

Dave

**Comment by mattalberts** [comment]
@vaamarnath @davecheney Thanks for the notes.  I've been building up the full solution over the last few days, adding tests, and verifying functionality.  I'll split up the change set into a few PRs, mirroring the suggestion to provide 1 per major design point.

**Comment by davecheney** [comment]
I think this issue is now complete, at least wrt. the 0.12 milestone. Thank you to @vaamarnath @mattalberts and @stevesloka for pushing this forward.
