### ISSUE TITLE
Provide option to supply a YAML file as Bootstrap envoy config input

### ISSUE THREAD

**Issue by shivanshu21** [heptio/contour#939]
**Describe the solution you'd like**
If there is an option to provide a YAML file as input to bootstrap mode contour, changes to bootstrap config will become YAML file change in helm rather than code changes to contour.

eg. contour bootstrap output.yaml /tmp/input_template.yaml --admin-port=8080

**Anything else you would like to add:**
I have implemented this as a minor fix in an internal repo. Please assign this to me if you see value in having this enhancement.

**Environment:**

- Contour version: v10 or v11
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by davecheney** [comment]
Hi @shivanshu21. Thank you for raising this issue.

I would prefer to not add this feature for the following reasons

1. `contour bootstrap` is only a convenience helper, from the Envoy container's point of view it expects to see a file on disk in the `/config` mountpoint, but it doesn't care how it got there. We use `contour bootstrap` in our example deployment yaml, but it is not required to use Contour.

2. Both the format of `contour bootstrap` and its contents change over time. I don't want to commit to an interface to programmatically template that as this may result in Contour being pinned to an arbitrary version of Envoy.
3. The configuration format isn't even YAML at the moment, we just support the `yaml` extension because most people upgrade Contour by editing their deployment and changing the image version; its unlikely they will change the extension from `.yaml` to `.json`. Fortunately Envoy does't care about the file extension. I don't want to commit to templating this file for the same reason as point 2, the interface is not stable.

Can you tell me more about the problem that you are trying to solve? If you can explain your requirements there may be a better solution than adding templating to `contour bootstrap`

**Comment by shivanshu21** [comment]
Right now we have a bunch of dynamic config for our envoy containers that we want to take in from kubernetes and put into envoy using contour.

But we also have a lot of *unchanging* configuration that we just want to dump into envoy config once and do not change very often.

One way to accomplish this is making code changes to contour in `/internal/envoy/config.go` to the string `const yamlConfig `.

Another way is to pull `const yamlConfig` out of contour and keep it as an external file (which may be a YAML). Later changes to the initial "unchanging" envoy config can just be made to this file.

Contour code need not be touched. New binaries need not be created. Another deployment need not be made.

**Comment by davecheney** [comment]
I’m sorry to say that const yamlConfig left the building in contour 0.10, along with the config file in yaml format.

**Comment by remmeier** [comment]
is there currently any way to reconfigure envoy? we have a similar use case, the `X-Forwarded-For` handling does not seem to work for us and we would like modify the configuration in that area (https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#x-forwarded-for).

**Comment by davecheney** [comment]
@remmeier can you please open a new issue with some details about what isn't working about `X-Forwarded-For`. Thank you.

**Comment by shivanshu21** [comment]
Thanks for the clarification Dave.
